### ISSUE TITLE
Delay when executing pkexec command from gnome-shell extensions.

### ISSUE THREAD

**Issue by maniacx** [polkit-org/polkit#510] opened 2024-10-14 22:55 UTC
**Describe the bug**

- In Wayland, when I install gnome-extensions that execute a command using pkexec, there is a delay of around 2 - 2.5 minutes.
- The gnome extension uses Gio.subprocess to run execute a using command and receive a response.  (For testing I used a simple command `pkexec uname -r`)
- When the command is executed, the dialog box for password is immediately displayed. Upon submitting the password, the command takes 2 - 2.5 minutes to complete a response is received. 

**Logs:**
I havent found anything strange in log using journalctl.
But Sysprof shows the following.
![Screenshot From 2024-10-11 21-30-02](https://github.com/user-attachments/assets/118262fd-d5e3-4939-bb8d-eaf5fb8e5038)

**Several things I have noted.**
- This issue affects only few distribution in Wayland. In Xorg there is no delay.
- This issue is present in Ubuntu 24.10 ( Gnome-shell 47, Polkit 124) and Debian (Gnome-shell 46, Polkit 125). 
- Fedora 41 beta (Gnome-shell 47, Polkit 125) running in Wayland doesn’t have this issue.  
- All distro running in Xorg doesn’t have this issue
- If the command `pkexec uname -r` is directly executed directly in bash terminal (Xorg/Wayland), the delay is not present
- If the same snippet of code is executed in gjs-console (Xorg/Wayland) using Gio.Subprocess that executes `pkexec uname -r`, the delay is not present.
- I noted that Fedora has wheel group, but Debian and Ubuntu doesn’t have this. I am not sure if this has something to do with the delay.

I was hoping someone could shed some light on what is going on, as I have been trying to figure out the issue, for few weeks now.

**Expected behavior**
There should be not delay in execution of command. If there is an issue with permission provided, it should be granted or denied, but not delayed.
.

**Desktop (please complete the following information):**
 - OS (including version): Ubuntu 24.10 / Debian Trixie
 - Desktop Environment [Gnome, KDE, ...]: Gnome 46/47
 - Version of polkit: 124/125

**Additional context**
https://github.com/maniacx/Battery-Health-Charging/issues/100#issuecomment-2325226386

https://github.com/maniacx/Battery-Health-Charging/issues/100#issuecomment-2302597513

https://github.com/maniacx/Battery-Health-Charging/issues/111

**Comment by maniacx** [comment] 2024-10-15 03:06
For context found wrap terminal also having similar issue.
See discussion here

https://github.com/warpdotdev/Warp/issues/5367

**Comment by jrybar-rh** [comment] 2024-10-31 14:50
The reporter found out the issue was not caused by polkit. Closing.

**Closed by jrybar-rh** 2024-10-31 14:50 UTC

**Comment by maniacx** [comment] 2024-11-01 06:43
@jrybar-rh 
The problem from gnome-shell extension is still not solved.
My extension and 3 other extension that I have tested have the same issue.

> The reporter found out the issue was not caused by polkit. Closing.

**Wrap** problem was not related to polkit, sorry for misleading information.


When running pkexec through gnome-shell process, It is tricky to find the what is the cause bug?
* **Issue or delay is only on Debian Trixie (Polkit 125 / Gnome 46)  and Ubuntu 24.10 (Polkit 124 / Gnome 47) running wayland**
* On Fedora 40 (Polkit 124/ Gnome 46), Xorg and Wayland, there is no issue, no delays. Works as expected
* On Debian Trixie (Polkit 125 / Gnome 46) Xorg works as expected.
* On Ubuntu 24.10 (Polkit 124 / Gnome 47) Xorg work as expected

I have be testing and going back and forth both on both systems,  Fedora 40 and Ubuntu 24.10 for past 2 weeks, trying to figure out why is it working on Fedora but not on debian/ubuntu.

- I thought it is polkit issue, but it works on Fedora wayland.
- I thought debian/ubuntu blocked use of pkexec on gnome-extensions using policies/rules, but they work extension works on Xorg.
- I though it is a gnome shell issue, but when the extension runs and execcutes command using pkexec, Gnome-polkit-agent dialog shows up immediatly, but upon usiing correct password, it takes  approx 150 seconds to execute the command.
- Also during these 150 seconds, my CPU fan gradually starts reving up.

I have been check `journalctl -f`, `sysprof` and `bustle` app, but I didnt find any strange behavior when comparing Xorg and Wayland and/or Fedora wayland vs ubuntu wayland.

To remove possiblity that the bug could be in my extension, I create a dummy test extension, when enabled will execute `pkexec uname -r` command using Gio.Subprocess and logs the ouptut. ( `jounalctl -f -o /usr/bin/gnome-shell` )

I know you are running Ubuntu, if you test the extension and may be you might figure out why it has a delay.
[test-pkexec.zip](https://github.com/user-attachments/files/17596847/test-pkexec.zip)

I would appreciate the help, with debugging this issue. 
But I would also understand, you do not want to assist or do not have time to check, and keep this issue closed.

**Comment by maniacx** [comment] 2024-11-04 03:24
![Screenshot From 2024-11-03 19-23-15](https://github.com/user-attachments/assets/ef27002b-3184-499b-8867-5cdd4445be8e)

**Comment by jrybar-rh** [comment] 2024-11-04 09:31
I installed Ubuntu on my spare Thinkpad (since I don't use ub) on Friday, in order to reproduce the issue, which didn't happen. No delay during boot or after enabling the extension or anything. Which was suspicious though, were two spawned `pkexec` processes that used up 100% on two cpu cores. After enabling the extension, the laptop fan went crazy.

**Comment by maniacx** [comment] 2024-11-04 16:52
There wont be delay in boot or enabling extension.
But there will be delay in response in the command. The extension will execute `pkexec  uname -r`command and the when uname -r completes it will log out the output.
You will have to monitor the log using.
```
journalctl -f -o cat /usr/bin/gnome-shell
```

Here is an example of what the extension does in Ubuntu Xorg. 

[Screencast From 2024-11-04 08-34-05.webm](https://github.com/user-attachments/assets/61648026-6a20-4a62-b95d-21ee94f04c30)

The response it immediately available.
But in wayland, there is a delay of 120 -150 seconds.

The delay happens only in Ubuntu 24.10 Wayland (polkit 124) and Debian Trixie Wayland (polkit 125)
In Ubuntu 24.10 Xorg and Debian Trixie Xorg, there is no delay.
But in Fedora 40 Wayland (polkit 124) there is no delay.
But in Fedora 41 Wayland (polkit 125) there is no delay.

Make me think there is some configuration issue in debian / ubuntu systems.
May something to do with pam or polkit or user/groups in regards to wayland. I know fedora has a `wheel` group, but I tried  added wheel to test but that didnt work, but again I have very little understanding about user groups and permission, so I might have not done it correctly.
Thank you @jrybar-rh for taking an interest.

**Comment by queenkjuul** [comment] 2025-06-25 06:58
I am running into this issue when spawning `pkexec` from a Node.js process on Ubuntu 25.04, running X11 and polkit 126.

```sh

➤➤➤➤➤➤ time pkexec uname -a
________________________________________________________
Executed in    1.32 secs      fish           external
   usr time    6.01 millis    0.37 millis    5.63 millis
   sys time    7.10 millis    1.46 millis    5.63 millis

➤➤➤➤➤➤ time node -p 'child_process.exec("pkexec uname -a", () => {})'
________________________________________________________
Executed in  163.67 secs    fish           external
   usr time   67.77 secs    0.13 millis   67.77 secs
   sys time   94.29 secs    1.18 millis   94.29 secs
```

`pkexec` spawns, uses 100% of 1 CPU core for ~120s, then the command executes successfully.

I'm having a hard time figuring out where the issue comes from, but i've tried various Node versions with the same results. It sounds like the same fundamental issue

**Comment by maniacx** [comment] 2025-06-25 08:20
> I am running into this issue when spawning `pkexec` from a Node.js process on Ubuntu 25.04, running X11 and polkit 126.
> 
> ➤➤➤➤➤➤ time pkexec uname -a
> ________________________________________________________
> Executed in    1.32 secs      fish           external
>    usr time    6.01 millis    0.37 millis    5.63 millis
>    sys time    7.10 millis    1.46 millis    5.63 millis
> 
> ➤➤➤➤➤➤ time node -p 'child_process.exec("pkexec uname -a", () => {})'
> ________________________________________________________
> Executed in  163.67 secs    fish           external
>    usr time   67.77 secs    0.13 millis   67.77 secs
>    sys time   94.29 secs    1.18 millis   94.29 secs
> `pkexec` spawns, uses 100% of 1 CPU core for ~120s, then the command executes successfully.
> 
> I'm having a hard time figuring out where the issue comes from, but i've tried various Node versions with the same results. It sounds like the same fundamental issue

You should consider opening a new issue, as I don't think they will reopen this one.

I made a mistake earlier by mentioning that another project (Wrap Terminal) had a polkit-related issue, without properly checking / investigating their issue.
Later, the Wrap Terminal developer resolved their problem, which turned out to be unrelated to polkit. Unfortunately, this gave the impression that my bug was also unrelated, which likely made my reports seem less credible.

![Image](https://github.com/user-attachments/assets/38be9f76-8428-4aa5-958d-ecaec837af6b)

However, I am still facing this issue. I’ve created a workaround patch and now ask Ubuntu/Debian users to manually install it after installing my Gnome - extension. The patch forces the extension to use sudo instead of polkit specifically on these systems.

It would be really helpful if the developers looked into this further.
Surprisingly, the issue only occurs on Debian and Ubuntu systems.


My problem is similar to your, delay in execution and high CPU during the delayed period.

Please open a new issue and link this issue as well for context.
